(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";var e=require("__________________0"),t=require("__________________________________________1"),o=require("_____________________________________________2"),r=require("_______________________3");angular.module("app",["ui.router","ui.bootstrap"]).config(e).directive("escape",t.forAttribute("escape")).directive("focus",o.forAttribute("focus")).value("storage",new r("todos-angularjs"));
},{"_______________________3":4,"__________________0":7,"__________________________________________1":2,"_____________________________________________2":3}],2:[function(require,module,exports){
"use strict";function e(e){return{link:function(t,i,n){var r=27;var c=n[e];c&&i.on("keydown",function(e){e.keyCode===r&&t.$apply(c)})}}}e.forAttribute=function(t){return function(){return e(t)}};module.exports=e;
},{}],3:[function(require,module,exports){
"use strict";function t(t,e){return{link:function(n,i,u){var c=n.$watch(u[e],function(e){e&&t(function(){i[0].focus()},0,!1)});i.on("$destroy",c)}}}t.forAttribute=function(e){return["$timeout",function(n){return t(n,e)}]};module.exports=t;
},{}],4:[function(require,module,exports){
"use strict";function t(t){this.storageID_=t}var o=require("_____________6");t.prototype=new o;t.prototype.get=function(){var t=localStorage&&localStorage.getItem(this.storageID_);var e=t?JSON.parse(t):o.prototype.get.call(this);return e};t.prototype.put=function(t){localStorage&&localStorage.setItem(this.storageID_,JSON.stringify(t));o.prototype.put.call(this,t)};module.exports=t;
},{"_____________6":5}],5:[function(require,module,exports){
"use strict";function t(){this.value_=void 0}t.prototype.get=function(){return this.value_};t.prototype.put=function(t){this.value_=t};module.exports=t;
},{}],6:[function(require,module,exports){
"use strict";function t(t,o,e,n){function d(){var o=t.newTodo.trim();if(o.length){t.todos.push({title:o,completed:!1});t.newTodo=""}}function i(o){t.editedTodo=o;t.originalTodo=angular.extend({},o)}function l(o){t.editedTodo=null;o.title=o.title.trim();o.title||t.removeTodo(o)}function s(o){var e=t.todos.indexOf(o);t.todos[e]=t.originalTodo;t.doneEditing(t.originalTodo)}function r(o){return t.editedTodo===o}function a(o){t.todos.splice(t.todos.indexOf(o),1)}function u(){t.todos=t.todos.filter(function(t){return!t.completed})}function c(o){t.todos.forEach(function(t){t.completed=!o})}function m(e,d){t.remainingCount=o("filter")(t.todos,{completed:!1}).length;t.completedCount=t.todos.length-t.remainingCount;t.allChecked=!t.remainingCount;e!==d&&n.put(t.todos)}function f(){switch(e.params.status){case"active":t.status="active";t.statusFilter={completed:!1};break;case"completed":t.status="completed";t.statusFilter={completed:!0};break;default:t.status="";t.statusFilter=null}}t.todos=n.get()||[];t.newTodo="";t.editedTodo=void 0;t.remainingCount=0;t.completedCount=0;t.allChecked=!1;t.status=null;t.statusFilter=null;t.addTodo=d;t.editTodo=i;t.doneEditing=l;t.revertEditing=s;t.testEditing=r;t.removeTodo=a;t.clearCompletedTodos=u;t.markAll=c;t.watchTodos=m;t.onFilterChange=f;t.$watch("todos",m,!0);t.$on("$stateChangeSuccess",f)}t.$inject=["$scope","$filter","$state","storage"];module.exports=t;
},{}],7:[function(require,module,exports){
"use strict";function o(o,t){t.otherwise("/");o.state("home",{url:"/:status",template:require("_______________4"),controller:require("___________________________5")})}o.$inject=["$stateProvider","$urlRouterProvider"];module.exports=o;
},{"___________________________5":6,"_______________4":8}],8:[function(require,module,exports){
module.exports='<section id="todoapp">\n    <header id="header">\n        <h1>todos</h1>\n        <form id="todo-form" ng-submit="addTodo()">\n            <input id="new-todo" placeholder="What needs to be done?" ng-model="newTodo" autofocus>\n        </form>\n    </header>\n    <section id="main" ng-show="todos && todos.length" ng-cloak>\n        <input id="toggle-all" type="checkbox" ng-model="allChecked" ng-click="markAll(allChecked)">\n        <label for="toggle-all">Mark all as complete</label>\n        <ul id="todo-list">\n            <li ng-repeat="todo in todos | filter:statusFilter track by $index" ng-class="{completed: todo.completed, editing: todo == editedTodo}">\n                <div class="view">\n                    <input class="toggle" type="checkbox" ng-model="todo.completed">\n                    <label ng-dblclick="editTodo(todo)">{{todo.title}}</label>\n                    <button class="destroy" ng-click="removeTodo(todo)"></button>\n                </div>\n                <form ng-submit="doneEditing(todo)">\n                    <input class="edit" ng-show="testEditing(todo)" ng-trim="false" ng-model="todo.title" escape="revertEditing(todo)" ng-blur="doneEditing(todo)" focus="testEditing(todo)">\n                </form>\n            </li>\n        </ul>\n    </section>\n    <footer id="footer" ng-show="todos && todos.length" ng-cloak>\n        <span id="todo-count"><strong>{{remainingCount}}</strong>\n            <ng-pluralize count="remainingCount" when="{ one: \'item left\', other: \'items left\' }"></ng-pluralize>\n        </span>\n        <ul id="filters">\n            <li>\n                <a ng-class="{selected: status == \'\'}" href="#/">All</a>\n            </li>\n            <li>\n                <a ng-class="{selected: status == \'active\'}" href="#/active">Active</a>\n            </li>\n            <li>\n                <a ng-class="{selected: status == \'completed\'}" href="#/completed">Completed</a>\n            </li>\n        </ul>\n        <button id="clear-completed" ng-click="clearCompletedTodos()" ng-show="completedCount">Clear completed ({{completedCount}})</button>\n    </footer>\n</section>\n';
},{}]},{},[1])


//# sourceMappingURL=index.js.map